name: Build

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rid: [osx-x64, osx-arm64, linux-x64, linux-arm64]
        include:
          - rid: osx-x64
            os: macos-latest
          - rid: osx-arm64
            os: macos-latest
          - rid: linux-x64
            os: ubuntu-latest
          - rid: linux-arm64
            os: ubuntu-24.04-arm
            
    name: Publish for ${{ matrix.rid }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish ${{ matrix.rid }}
        run: |
          dotnet publish -c Release -r ${{ matrix.rid }} -o publish/${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitignore-${{ matrix.rid }}
          path: publish/${{ matrix.rid }}/